Landmarks/Landmarks.Web/Controllers/CategoryController.cs
using Landmarks.Common.Models.Main.ViewModels;
using Landmarks.Interfaces.Main;
using Landmarks.Web.Common.Helpers;
using Microsoft.AspNetCore.Mvc;

namespace Landmarks.Web.Controllers
{
    public class CategoryController : Controller
    {
        private const int DefaultPageSize = 5;
        private readonly ICategoryService _service;

        public CategoryController(ICategoryService service)
        {
            this._service = service;
        }

        [HttpGet]
        public IActionResult List(int? pageIndex)
        {
            var viewModel = this._service.GetCategories();
            int pageSize = DefaultPageSize;

            var result = PaginatedList<ListCategoriesViewModel>.Create(viewModel, pageIndex ?? 1, pageSize);
            return View(result);  
        }

        [HttpGet]
        public IActionResult LandmarksByCategory(int? id)
        {
            if (!id.HasValue) return NotFound();

            var viewModel = this._service.GetLandmarksByCategory(id.Value);

            if (viewModel is null) return NotFound();

            return View(viewModel);
        }
    }
}

Landmarks/Landmarks.Web/Controllers/CommentsController.cs
using System.Linq;
using Landmarks.Common.Models.Main.ViewModels;
using Landmarks.Interfaces.Main;
using Landmarks.Web.Common.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace Landmarks.Web.Controllers
{
    public class CommentsController : Controller
    {
        private readonly ICommentsService _service;

        public CommentsController(ICommentsService service)
        {
            this._service = service;
        }

        public ActionResult GetUsers()
        {
            return View();
        }

        public ActionResult GetUsers(string email)
        {
            var user = this._service.GetUserByEmail(email);

            return View(user);
        }

        public PartialViewResult GetComments(int landmarkId)
        {
            var comments = this._service.GetLandmarksComment(landmarkId);

            return PartialView("~/Views/Shared/_MyComments.cshtml", comments);
        }

        [HttpPost]
        public ActionResult AddComment(CommentsViewModel comment, int landmarkId)
        {
            var userId = this.User.GetUserId();
            this._service.SaveComment(userId, landmarkId, comment);

            return RedirectToAction("GetComments", "Comments", new { landmarkId = landmarkId });
        }

        public PartialViewResult GetSubComments(int commentId)
        {
            var subComments = this._service.GetSubComments(commentId);

            return PartialView("~/Views/Shared/_MySubComments.cshtml", subComments);
        }

        [HttpPost]
        public ActionResult AddSubComment(SubCommentsViewModel subComment, int commentId)
        {
            var userId = this.User.GetUserId();
            this._service.SaveSubComment(userId, subComment, commentId);

            return RedirectToAction("GetSubComments", "Comments", new { commentId = commentId });

        }
    }
}

Landmarks/Landmarks.Web/Controllers/LandmarkController.cs
using Landmarks.Interfaces.Main;
using Landmarks.Web.Common.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Landmarks.Web.Controllers
{
    public class LandmarkController : Controller
    {
        private readonly ILandmarkService _service;

        public LandmarkController(ILandmarkService service)
        {
            this._service = service;
        }

        public IActionResult Details(int id)
        {
            var viewModel = this._service.GetLandmarkById(id);

            return View(viewModel);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult RateLandmark(IFormCollection form)
        {
            var rating = int.Parse(form["Rating"]);
            var landmarkId = int.Parse(form["landmarkId"]);

            if (rating != 0)
            {
                var landmark = this._service.GetLandmarkFromDbById(landmarkId);
                landmark.RatingSum += rating;
                landmark.RatingCount++;
                landmark.Rating = landmark.RatingSum / landmark.RatingCount;
                // Getting the ID of the currently logged in user
                var currentUserId = this.User.GetUserId();
                // Adding the ID to the IDs of the users that have already rated this picture
                landmark.UserIdsRatedPic += " " + currentUserId;

                this._service.SaveRate(landmark);
            }

            return RedirectToAction("Details", new { id = landmarkId });
        }
    }
}

Landmarks/Landmarks.Web/Views/Shared/DisplayTemplates/CommentsViewModel.cshtml
@model CommentsViewModel
@inject IStringLocalizer<LandmarkController> Localizer

<article class="row">
    <div class="col-md-10 col-sm-10" style="margin:20px">
        <div class="panel panel-default arrow left">
            <div class="panel-body">
                <header class="text-left">
                    <div class="comment-user"><i class="fa fa-user"></i> @Model.Users.Email</div>
                    <time class="comment-date" datetime="16-12-2014 01:05"><i class="fa fa-clock-o"></i>@string.Format("{0:ddd, MMM d, yyyy}", Model.CommentedDate)</time>
                </header>
                <div class="comment-post">
                    <p>
                        @Model.CommentMsg
                    </p>
                </div>
                <p class="text-right"><button type="button" class="Reply btn secondary-color  btn-sm" data-id="@Model.Id"><i class="fa fa-reply"></i>@Localizer["btnAddNewComment"]</button></p>
                
                <div class="@string.Format("{0}_{1}", "ReplayComments", Model.Id)" style="display:none;">
                    <div class="ReplayCommentInput" style="margin-left: 3%;  margin-bottom: 5px; margin-top: 8px;">
                        <input type="text" id="@string.Format("{0}_{1}", "inputReplay", Model.Id)" class="form-control" placeholder="Add a Comment ..." style="display: inline;" />
                        <button type="button" class="btn btn-sm secondary-color ReplyAddComment" data-id="@Model.Id"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span>@Localizer["btnAddNewComment"]</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</article>

Landmarks/Landmarks.Web/Views/Shared/DisplayTemplates/LandmarkConciseViewModel.cshtml
@model LandmarkConciseViewModel

@inject IStringLocalizer<RegionController> Localizer;

<div class="row">
    <div class="col-lg-5 col-xl-4">
        <div class="view overlay rounded z-depth-1-half mb-lg-0 mb-4">
            <img class="img-fluid" src="@(Url.Content(Model.MainPagePath))" alt="Sample image">
            <a>
                <div class="mask rgba-white-slight"></div>
            </a>
        </div>
    </div>
    <div class="col-lg-7 col-xl-8">
        <h3 class="font-weight-bold mb-3">
            <strong>@Model.Name </strong>
        </h3>
        <p class="dark-grey-text">@Model.Description</p>
        <div class="personal-sm">
            <div>
                @Localizer["lblCategoryName"]: <strong>@Model.CategoryName</strong>
            </div>
            <div>
                @Localizer["lblRegionName"]: <strong>@Model.RegionName</strong>
            </div>
        </div>
        <p>@Localizer["lblBy"] <a class="font-weight-bold">@Model.CreatorEmail</a>, <i class="fa fa-clock-o"></i>@string.Format("{0:ddd, MMM d, yyyy}", Model.CreatedDate)</p>
        <a asp-area="" asp-controller="Landmark" asp-action="Details" asp-route-id="@Model.LandmarkId" class="btn secondary-color btn-sm">@Localizer["btnDetails"]</a>
    </div>
</div>
<hr class="my-5">

Landmarks/Landmarks.Web/Views/Shared/DisplayTemplates/LandmarkRankingViewModel.cshtml
@model LandmarkRankingViewModel

@inject IStringLocalizer<RankingController> Localizer
<tr>
    <td>@Model.Name</td>
    <td>@Model.CategoryName</td>
    <td>@Model.RegionName</td>
    <td>@Model.PostedDate</td>
    <td>@Model.VisitorsCount @Localizer["lblPeople"]</td>
    <td>@Model.DesireToVisitCount @Localizer["lblPeople"]</td>
    <td>
        <a asp-area="" asp-controller="Landmark" asp-action="Details" asp-route-id="@Model.Id" class="btn secondary-color btn-sm">@Localizer["btnDetails"]</a>
    </td>
</tr>

Landmarks/Landmarks.Web/Views/Shared/DisplayTemplates/ListCategoriesViewModel.cshtml
@model ListCategoriesViewModel

@inject IStringLocalizer<CategoryController> Localizer
<tr>
    <td>@Model.Name</td>
    <td>@Model.LandmarksCount</td>
    <td>
        <a asp-area="" asp-controller="Category" asp-action="LandmarksByCategory" asp-route-id="@Model.Id" class="btn btn-warning btn-sm">@Localizer["btnAll"]</a>
    </td>
</tr>

Landmarks/Landmarks.Web/Views/Shared/DisplayTemplates/SubCommentsViewModel.cshtml
@model SubCommentsViewModel

<div class="row" style="width: 100.3%; border-bottom: 1px solid #d2cece; margin-right: -14px; margin-left: -1px;">
    <div class="col-md-3" style="width: 36%;">
        <div class="userProfil" style="margin-left: 9px; margin-top: 12px;">
            <p style="margin-left: 5px; font-weight: bold; font-size: 13px;"> @Model.User.Email </p>
        </div>
    </div>
    <div class="col-md-6" style="width: 32%;">
        <div class="commentDetails">
            <p style="margin-top: 27px; font-size: 13px; color: #9c9898;"> @Model.CommentMsg </p>
        </div>
    </div>
    <div class="col-md-3">
        <div class="commentDetails">
            <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
            <time class="comment-date" datetime="16-12-2014 01:05"><i class="fa fa-clock-o"></i>@string.Format("{0:ddd, MMM d, yyyy}", Model.CommentedDate)</time>
        </div>
    </div>
</div>