Landmarks/Landmarks.Web/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Landmarks.Web.Areas.Admin.Controllers
{
    public class HomeController : AdminController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Landmarks/Landmarks.Web/Areas/Operator/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Landmarks.Web.Areas.Operator.Controllers
{
    public class HomeController : OperatorController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Landmarks/Landmarks.Web/Controllers/HomeController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Landmarks.Interfaces;

namespace Landmarks.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IMainService _service;

        public HomeController(IMainService service)
        {
            this._service = service;
        }

        public IActionResult Index()
        {
            return View();
        }

        public JsonResult GetRegionInfo(string regionName)
        {
            var regionInfo = this._service.GetRegionInfoByName(regionName);

            if (regionInfo == null) return Json(null);
            var result = Json(regionInfo.Id);
            return result;
        }
            
        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
    }
}

Landmarks/Landmarks.Web/Controllers/RegionController.cs
using Landmarks.Interfaces.Main;
using Microsoft.AspNetCore.Mvc;

namespace Landmarks.Web.Controllers
{
    public class RegionController : Controller
    {
        private readonly IRegionService _service;

        public RegionController(IRegionService service)
        {
            this._service = service;
        }

        public IActionResult Details(int? id)
        {
            if (id is null) return NotFound();

            var viewModel = this._service.GetRegionById(id.Value);

            if (viewModel is null) return NotFound();

            return View(viewModel);
        }
    }
}

Landmarks/Landmarks.Web/Views/Home/Index.cshtml
@inject IStringLocalizer<HomeController> Localizer;

@{
    ViewData["Title"] = Localizer["lblHome"];
}

<div class="jsmaps-wrapper" id="world-map"></div>

<script type="text/javascript">

    $(function () {

        $('#world-map').JSMaps({
            map: 'bulgaria'
        });

    });
</script>

<script>
    $(document).ready(function () {

        var regionDesc = {
        "Vidin": "@Localizer["descVidin"]",
        "Montana":"@Localizer["descMontana"]" ,
        "Vratsa": "@Localizer["descVratsa"]",
        "Pleven": "@Localizer["descPleven"]",
        "Veliko Tarnovo": "@Localizer["descVelikoTarnovo"]",
        "Ruse": "@Localizer["descRuse"]",
        "Razgrad": "@Localizer["descRazgrad"]",
        "Silistra": "@Localizer["descSilistra"]",
        "Dobrich": "@Localizer["descDobrich"]",
        "Varna": "@Localizer["descVarna"]",
        "Shumen": "@Localizer["descShumen"]",
        "Targovishte": "@Localizer["descTargovishte"]",
        "Gabrovo": "@Localizer["descGabrovo"]",
        "Lovech": "@Localizer["descLovech"]",
        "Sofia": "@Localizer["descSofia"]",
        "Pernik": "@Localizer["descPernik"]",
        "Kyustendil": "@Localizer["descKyustendil"]",
        "Blagoevgrad": "@Localizer["descBlagoevgrad"]",
        "Pazardzhik": "@Localizer["descPazardzhik"]",
        "Plovdiv": "@Localizer["descPlovdiv"]",
        "Stara Zagora": "@Localizer["descStaraZagora"]",
        "Smolyan": "@Localizer["descSmolyan"]",
        "Kardzhali": "@Localizer["descKardzhali"]",
        "Sliven": "@Localizer["descSliven"]",
        "Yambol": "@Localizer["descYambol"]",
        "Burgas": "@Localizer["descBurgas"]",
        "Grad Sofiya": "@Localizer["descSofia"]",
        "Haskovo":"@Localizer["descHaskovo"]"

    };

    $('path').on("click", function () {
        var selectedElement = $('.jsmaps-select.mobile').find('select :selected');
        var regionName = selectedElement.val();

        $.ajax({
            url: "@(Url.Action("GetRegionInfo", "Home"))",
            dataType: "text",
            contentType: "application/json",
            data: { 'regionName': regionName },
            async: false,
            success: function (response) {
                debugger;
                var element = $($('.jsmaps-text')[0]);
                var regionId = JSON.parse(response);

                var htmlAsString = '<div class="card col col-md-12">';
                htmlAsString += '<div class="view overlay">';
                htmlAsString += '</div ><div class="card-body">';
                htmlAsString += '<h4 class="card-title">' + regionName + '</h4>';

                htmlAsString += '<p class="card-text"> ' + regionDesc[regionName] + ' </p>';

                if (regionId) {
                    htmlAsString += '<a id="regionLink" class="btn secondary-color" href="#">@Localizer["btnReadMore"]</a>';
                }

                htmlAsString += '</div></div >';

                element.empty();
                element.append($.parseHTML(htmlAsString));

                if (regionId) {
                    var link = '@Url.Action("Details", "Region", new { id = "-1" })';
                    link = link.replace("-1", regionId);
                    $('#regionLink').attr('href', link);
                }
            }, error: function (xhr, textStatus, errorThrown) {
                console.log(xhr);
                console.log(textStatus);
                console.log(errorThrown);
            }
        });
    });
});
</script>